version: '3'
services:
 app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Your-Password-Here
      - MYSQL_DATABASE=graphQLTesting
    depends_on:
      - mysql

 mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Your-Password-Here
      MYSQL_DATABASE: graphQLTesting
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
 mysql_data:
